package com.endiar.anyrecipes.utils

import com.endiar.anyrecipes.R
import com.endiar.anyrecipes.model.FridgeIngredientItem

object Data {
    val fridgeData = listOf(
        FridgeIngredientItem(
            1,
            "beef",
            "Beef",
            R.drawable.ic_ingredient_beef
        ),
        FridgeIngredientItem(
            2,
            "chicken",
            "Chicken",
            R.drawable.ic_ingredient_chicken
        ),
        FridgeIngredientItem(
            3,
            "crab",
            "Crab",
            R.drawable.ic_ingredient_crab
        ),
        FridgeIngredientItem(
            4,
            "egg",
            "Eggs",
            R.drawable.ic_ingredient_eggs
        ),
        FridgeIngredientItem(
            5,
            "fish",
            "Fish",
            R.drawable.ic_ingredient_fish
        ),
        FridgeIngredientItem(
            6,
            "lobster",
            "Lobster",
            R.drawable.ic_ingredient_lobster
        ),
        FridgeIngredientItem(
            7,
            "octopus",
            "Octopus",
            R.drawable.ic_ingredient_octopus
        ),
        FridgeIngredientItem(
            8,
            "pasta",
            "Pasta",
            R.drawable.ic_ingredient_pasta
        ),
        FridgeIngredientItem(
            9,
            "sausage",
            "Sausage",
            R.drawable.ic_ingredient_sausage
        ),
        FridgeIngredientItem(
            10,
            "shrimp",
            "Shrimp",
            R.drawable.ic_ingredient_shrimp
        ),
        FridgeIngredientItem(
            11,
            "squid",
            "Squid",
            R.drawable.ic_ingredient_squid
        ),
        FridgeIngredientItem(
            12,
            "tofu",
            "Tofu",
            R.drawable.ic_ingredient_tofu
        )
    )
}